# pytorch を用いて機械学習に入門する(その１：超基本)
このノートではまず、pytorchを用いて基本的なチュートリアルをクリアしていきたい。

pytorchの公式レファレンス
https://pytorch.org/docs/stable/index.html

以下の`torch.manual_seed(SEED)`は乱数生成のシードを渡す文である。
https://pytorch.org/docs/stable/generated/torch.manual_seed.html

In [1]:
import numpy as np
import torch
SEED=123
np.random.seed(SEED)
torch.manual_seed(SEED)

## torch.Tensor クラス
Pytorchでテンソルを定義する。`torch.Tensor`はpytorchで提供されるテンソルのデータ型である。各要素は全て同じ型であることが要求される。
クラス型変数ということ？

https://pytorch.org/docs/stable/tensors.html

にあるように、CPU,GPUそれぞれに対しても違う方が提供されていたりする。

In [3]:
t=torch.zeros(2,3)
print('torch.zeros:\n',t)
print(type(t))

torch.zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>


In [5]:
t=torch.ones(3,2)
print('\ntorch.ones:\n',t)
print(type(t))


torch.ones:
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
<class 'torch.Tensor'>


## torch.arange
https://pytorch.org/docs/stable/generated/torch.arange.html#torch.arange

In [9]:
t=torch.arange(0,6,1)
print('\ntorch.arange:\n',t)

t=torch.arange(0,6,1).reshape(2,3).float()
print('\ntorch.arange with reshape and cast to float:\n',t)
print(type(t))


torch.arange:
 tensor([0, 1, 2, 3, 4, 5])

torch.arange with reshape and cast to float:
 tensor([[0., 1., 2.],
        [3., 4., 5.]])
<class 'torch.Tensor'>


In [11]:
t=torch.randn(2,3)
print('\ntorch.randn:\n',t)


torch.randn:
 tensor([[-0.9724, -0.7550,  0.3239],
        [-0.1085,  0.2103, -0.3908]])


## numpyからtorch.Tensorを作成

In [19]:
np_mat = np.eye(5, M=None, k=0, dtype=float)
print('\nnumpy unit mat:\n',np_mat)

# data_np = np.zeros([10,10],dtype=np.float32)
# np.fill_diagonal(data_np,1.)

torch_mat = torch.Tensor(np_mat)
print('\ntorch unit mat:\n',torch_mat)


numpy unit mat:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

torch unit mat:
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


## torch.Tensorをnumpy arrayに変換
torch.Tensorクラスにはnumpy()というメソッドが用意されており、これでNumpy arrayに変換する。

In [20]:
torch_mat.numpy()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

基本の統計操作は、Numpyと同じようにtorch.Tensorにもメソッドが用意されている。item()メソッドはスカラー量を数値として取得する。

In [26]:
print('mean',torch_mat.mean(),'std',torch_mat.std(),'sum',torch_mat.sum())
print('mean',torch_mat.mean().item(),'std',torch_mat.std().item(),'sum',torch_mat.sum().item())

mean tensor(0.2000) std tensor(0.4082) sum tensor(5.)
mean 0.20000000298023224 std 0.40824830532073975 sum 5.0


## 基本の演算
まず、numpyで行列を定義し、torch.Tensorに変換する。

In [31]:
data1 = np.zeros([3,3],dtype=np.float32)
np.fill_diagonal(data1,1.)
torch1 = torch.Tensor(data1)

data2 = np.zeros([3,3],dtype=np.float32)
data2[0,:]=1.
torch2 = torch.Tensor(data2)

print(torch1,"\n\n",torch2)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]) 

 tensor([[1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [32]:
# Elementwise multiplication
print(torch1*torch2)

tensor([[1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [35]:
# Matrix multiplication
print(torch1.matmul(torch2))

tensor([[1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [39]:
# Elemetwise Addision
print(torch1+1)

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])


In [40]:
# Matrix addition
print(torch1-torch2)

tensor([[ 0., -1., -1.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]])


## GPUの利用に関して
pytorchではGPU計算で使える形にするには次のように簡単にできる。
pytorch.Tensorには、cuda()というメソッドが用意されている。これを呼ぶことでGPU計算に使えるデータ型でインスタンスを生成できる。

In [41]:
# Create 1000x1000 matrix
data_np=np.zeros([1000,1000],dtype=np.float32)
data_cpu = torch.Tensor(data_np).cpu()
data_gpu = torch.Tensor(data_np).cuda()

In [42]:
%%timeit
mean = (data_cpu ** 5).mean().item()

2.36 ms ± 316 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [43]:
%%timeit
mean = (data_gpu ** 5).mean().item()

181 µs ± 4.81 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
