# pytorch を用いて機械学習に入門する(その２：公式チュートリアル)

Pythorchよく分からないから公式のチュートリアルでも見てみる。
https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

## Autogradに関して
https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html#sphx-glr-beginner-blitz-autograd-tutorial-py

`torch.Tensor` クラスには`.requires_grad` というアトリビュートが存在しており、これをTrueにすると、このインスタンスの変化をトラックする。

In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


yはxに操作を施して作られたテンソルである。xは`requires_grad=True`にしていたので、そこからの操作で作られたテンソルは`grad_fn`を持つ。

In [4]:
print(y.grad_fn)

In [5]:
z = y * y * 3
out = z.mean()

print(z,"\n\n",out,"\n")
print(z.grad_fn)
print(out.grad_fn)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) 

 tensor(27., grad_fn=<MeanBackward0>) 



In [6]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad) # requires_grad is false in dafault
a.requires_grad_(True)
print(a.requires_grad)
a = (a * a).sum()
print(a.grad_fn)

False
True


## Gradient

In [7]:
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [8]:
out.backward()

In [9]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [10]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ 209.7022,  922.3116, -727.9885], grad_fn=<MulBackward0>)


In [11]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


## Neural Network
全てのモデルはnn.Moduleのサブクラスでなければならない。
https://pytorch.org/docs/stable/generated/torch.nn.Module.html

In [12]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
class MyNet(nn.Module):
    
    def __init__(self):
        #全てのモデルはnn.Moduleを継承していなければならない。superは親クラスのメソッドを呼び出すのに使う。つまりここでは nn.Moduleの__init__()を呼び出している。
        super().__init__() 
        
        # 1 input image channel, 6 output channels, 3x3 square kernel 
        self.conv1 = nn.Conv2d(1,6,3)
        
        self.conv2 = nn.Conv2d(6, 16, 3)
        
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)